"""GAMES_SCHEMA: schedule dimension table (one row per game)."""

from __future__ import annotations

from nhl_bigquery.schema import ColumnSpec, PartitioningSpec


def get_partitioning() -> PartitioningSpec:
    return PartitioningSpec(
        field="game_date", type="DAY", clustering=["season", "game_type"],
    )


def _col(name, type, mode, short, defn, *, tags=None, range_=None, values=None,
         example=None, gotchas=None, api_eq=None, api_src=None, dep=None):
    return ColumnSpec(
        name=name, type=type, mode=mode,
        short_description=short, business_definition=defn,
        semantic_tags=list(tags or []),
        valid_range=range_, valid_values=values, example_value=example,
        gotchas=list(gotchas or []),
        nhl_api_equivalent=api_eq, nhl_api_source_field=api_src or name,
        deprecated_in_year=dep,
    )


GAMES_SCHEMA: list[ColumnSpec] = [
    _col("game_id", "INT64", "REQUIRED",
         "NHL unique game identifier.",
         "Stable integer identifying a single NHL game. Canonical join key to nhl_plays / boxscore_stats / shifts.",
         tags=["identifier", "join_key"], example=2024020001,
         api_eq="id", api_src="id"),
    _col("game_date", "DATE", "REQUIRED",
         "Date the game was played.",
         "Calendar date of the game (game local). Partition key for this table.",
         tags=["temporal", "identifier"], example="2024-10-08",
         api_eq="gameDate", api_src="gameDate"),
    _col("season", "INT64", "REQUIRED",
         "Season start year (e.g. 2024 for 2024-25).",
         "Four-digit start year of the season. The 2024-25 season is season=2024.",
         tags=["temporal", "identifier"], range_=(2010.0, 2050.0), example=2024,
         api_eq="season (first 4 digits)", api_src="season"),
    _col("game_type", "STRING", "NULLABLE",
         "Game type code (PR/R/P/AS).",
         "Game type derived from the game_id type digit: PR=preseason, R=regular, P=playoffs, AS=all-star.",
         tags=["identifier"], values=["PR", "R", "P", "AS"], example="R",
         api_eq="gameType (numeric → coded)", api_src="gameType"),
    _col("home_team_id", "INT64", "REQUIRED",
         "Home team ID.",
         "NHL team ID for the home team in this game.",
         tags=["identifier", "join_key", "team"], example=10,
         api_eq="homeTeam.id", api_src="homeTeam.id"),
    _col("away_team_id", "INT64", "REQUIRED",
         "Away team ID.",
         "NHL team ID for the away team in this game.",
         tags=["identifier", "join_key", "team"], example=6,
         api_eq="awayTeam.id", api_src="awayTeam.id"),
    _col("home_team_abbrev", "STRING", "NULLABLE",
         "Home team 3-letter abbreviation.",
         "Three-letter abbreviation for the home team (TOR, NYR, ...).",
         tags=["team"], example="TOR",
         gotchas=["Abbreviations changed for relocations (ARI → UTA in 2024)."],
         api_eq="homeTeam.abbrev", api_src="homeTeam.abbrev"),
    _col("away_team_abbrev", "STRING", "NULLABLE",
         "Away team 3-letter abbreviation.",
         "Three-letter abbreviation for the away team.",
         tags=["team"], example="MTL",
         api_eq="awayTeam.abbrev", api_src="awayTeam.abbrev"),
    _col("venue_default_name", "STRING", "NULLABLE",
         "Venue name (English).",
         "Default-locale (English) name of the venue where the game was played.",
         tags=["venue"], example="Scotiabank Arena",
         api_eq="venue.default", api_src="venue.default"),
    _col("start_time_utc", "TIMESTAMP", "NULLABLE",
         "Scheduled puck-drop in UTC.",
         "Scheduled or actual start time in UTC.",
         tags=["temporal"], example="2024-10-08T23:00:00Z",
         api_eq="startTimeUTC", api_src="startTimeUTC"),
    _col("eastern_utc_offset", "STRING", "NULLABLE",
         "Eastern UTC offset for the game date.",
         "Eastern Time UTC offset (e.g. '-04:00'). Useful for converting to NHL canonical Eastern time.",
         tags=["temporal"], example="-04:00",
         api_eq="easternUTCOffset", api_src="easternUTCOffset"),
    _col("venue_utc_offset", "STRING", "NULLABLE",
         "Venue local UTC offset.",
         "UTC offset of the venue at game time (e.g. '-07:00').",
         tags=["temporal"], example="-07:00",
         api_eq="venueUTCOffset", api_src="venueUTCOffset"),
    _col("game_state", "STRING", "NULLABLE",
         "Game state (FUT/PRE/LIVE/CRIT/FINAL/OFF).",
         "Lifecycle state of the game. FUT=scheduled-future, PRE=pre-game, LIVE=in-progress, CRIT=last-minute, FINAL=just-ended, OFF=archived.",
         tags=["status"], values=["FUT", "PRE", "LIVE", "CRIT", "FINAL", "OFF"], example="OFF",
         gotchas=["Filter game_state IN ('FINAL','OFF') for completed games."],
         api_eq="gameState", api_src="gameState"),
    _col("final_period_type", "STRING", "NULLABLE",
         "Period type at game end (REG/OT/SO).",
         "Type of the last period played. REG=ended in regulation, OT=overtime decided, SO=shootout decided.",
         tags=["status"], values=["REG", "OT", "SO"], example="REG",
         api_eq="gameOutcome.lastPeriodType", api_src="gameOutcome.lastPeriodType"),
    _col("home_score_final", "INT64", "NULLABLE",
         "Home team final score.",
         "Goals scored by the home team at game end (including any shootout decider).",
         tags=["score_state"], range_=(0.0, 20.0), example=4,
         api_eq="homeTeam.score", api_src="homeTeam.score"),
    _col("away_score_final", "INT64", "NULLABLE",
         "Away team final score.",
         "Goals scored by the away team at game end.",
         tags=["score_state"], range_=(0.0, 20.0), example=3,
         api_eq="awayTeam.score", api_src="awayTeam.score"),
    _col("is_shootout_decided", "BOOL", "NULLABLE",
         "Was the game decided in a shootout?",
         "Derived: final_period_type == 'SO'. Convenience flag for filtering shootout games out of skater stats.",
         tags=["status"], example=False,
         api_eq=None, api_src="(derived)"),
    _col("ingested_at", "TIMESTAMP", "REQUIRED",
         "Ingestion timestamp.",
         "UTC timestamp when this row was written by nhl-bigquery sync.",
         tags=["meta"], example="2026-05-22T17:00:00Z",
         api_eq=None, api_src="(set by ingestion)"),
]
