"""BOXSCORE_SCHEMA: per-player per-game stats (skaters + goalies)."""

from __future__ import annotations

from nhl_bigquery.games.schema import _col
from nhl_bigquery.schema import ColumnSpec, PartitioningSpec


def get_partitioning() -> PartitioningSpec:
    return PartitioningSpec(
        field="game_date", type="DAY", clustering=["player_id", "team_id"],
    )


BOXSCORE_SCHEMA: list[ColumnSpec] = [
    # Common
    _col("game_id", "INT64", "REQUIRED", "NHL game ID.",
         "FK to games.game_id.", tags=["identifier", "join_key"], example=2024020001,
         api_eq="id", api_src="id"),
    _col("game_date", "DATE", "REQUIRED", "Game date.",
         "Partition key for this table.", tags=["temporal"], example="2024-10-08",
         api_eq="gameDate", api_src="gameDate"),
    _col("player_id", "INT64", "REQUIRED", "NHL Player ID.",
         "Canonical player identifier; FK to player landing API.",
         tags=["identifier", "join_key"], example=8478402,
         api_eq="playerId", api_src="playerId"),
    _col("team_id", "INT64", "REQUIRED", "Team ID this game.",
         "NHL team_id of the team the player suited up for. "
         "Mid-season trades produce different team_ids across games.",
         tags=["identifier", "join_key", "team"], example=10,
         api_eq="(side teamId)", api_src="(side teamId)"),
    _col("player_position_category", "STRING", "REQUIRED",
         "Discriminator: 'skater' or 'goalie'.",
         "Splits skater rows (with G/A/+-/PIM/...) from goalie rows (SA/SV/SV%/GAA/...).",
         tags=["identifier"], values=["skater", "goalie"], example="skater",
         api_eq="(derived: 'forwards'/'defense'/'goalies' bucket)",
         api_src="(derived)"),
    _col("position_code", "STRING", "NULLABLE", "Position code (C/L/R/D/G).",
         "Single-letter position: C=center, L=left wing, R=right wing, D=defense, G=goalie.",
         tags=["identifier"], values=["C", "L", "R", "D", "G"], example="C",
         api_eq="position", api_src="position"),
    _col("sweater_number", "INT64", "NULLABLE", "Jersey number worn this game.",
         "Sweater number; not stable across trades.",
         tags=["identifier"], range_=(1.0, 99.0), example=97,
         api_eq="sweaterNumber", api_src="sweaterNumber"),
    _col("toi", "STRING", "NULLABLE", "Time on ice (MM:SS).",
         "Total time on ice. String MM:SS to preserve fidelity; use toi_seconds for arithmetic.",
         tags=["measure"], example="20:34",
         api_eq="toi", api_src="toi"),
    # Skater-only
    _col("goals", "INT64", "NULLABLE", "Goals scored.",
         "Goals scored by this skater in this game.", tags=["measure"], example=1,
         api_eq="goals", api_src="goals"),
    _col("assists", "INT64", "NULLABLE", "Assists.",
         "Assists in this game.", tags=["measure"], example=2,
         api_eq="assists", api_src="assists"),
    _col("points", "INT64", "NULLABLE", "Points (G + A).",
         "Goals + assists. Stored directly to avoid query-time arithmetic.",
         tags=["measure"], example=3, api_eq="points", api_src="points"),
    _col("plus_minus", "INT64", "NULLABLE", "Plus/minus.",
         "Plus/minus for this skater in this game.", tags=["measure"], example=2,
         api_eq="plusMinus", api_src="plusMinus"),
    _col("pim", "INT64", "NULLABLE", "Penalty minutes.",
         "Penalty minutes assessed to this player.", tags=["measure"], example=0,
         api_eq="pim", api_src="pim"),
    _col("hits", "INT64", "NULLABLE", "Hits delivered.", "Body checks delivered.",
         tags=["measure"], example=3, api_eq="hits", api_src="hits"),
    _col("blocked_shots", "INT64", "NULLABLE", "Shots blocked.",
         "Shots the player blocked.", tags=["measure"], example=1,
         api_eq="blockedShots", api_src="blockedShots"),
    _col("shots", "INT64", "NULLABLE", "Shots on goal.",
         "Shots on goal (SOG); does not include missed or blocked shots.",
         tags=["measure"], example=4, api_eq="shots", api_src="shots"),
    _col("faceoffs", "INT64", "NULLABLE", "Faceoffs taken.",
         "Total faceoffs taken (won + lost).", tags=["measure"], example=10,
         api_eq="faceoffs", api_src="faceoffs"),
    _col("faceoff_winning_pctg", "FLOAT64", "NULLABLE", "Faceoff win %.",
         "Faceoff winning percentage as a decimal (0.0-1.0).",
         tags=["measure"], range_=(0.0, 1.0), example=0.55,
         api_eq="faceoffWinningPctg", api_src="faceoffWinningPctg"),
    _col("power_play_goals", "INT64", "NULLABLE", "Power-play goals.",
         "Goals scored while on the power play.", tags=["measure"], example=1,
         api_eq="powerPlayGoals", api_src="powerPlayGoals"),
    _col("power_play_points", "INT64", "NULLABLE", "Power-play points.",
         "Goals + assists earned while on the power play.",
         tags=["measure"], example=2, api_eq="powerPlayPoints", api_src="powerPlayPoints"),
    _col("shorthanded_goals", "INT64", "NULLABLE", "Shorthanded goals.",
         "Goals scored while shorthanded.", tags=["measure"], example=0,
         api_eq="shorthandedGoals", api_src="shorthandedGoals"),
    _col("sh_points", "INT64", "NULLABLE", "Shorthanded points.",
         "Goals + assists earned while shorthanded.", tags=["measure"], example=0,
         api_eq="shPoints", api_src="shPoints"),
    _col("power_play_toi", "STRING", "NULLABLE", "Power-play TOI.",
         "Time on ice while on the power play (MM:SS).",
         tags=["measure"], example="2:14",
         api_eq="powerPlayToi", api_src="powerPlayToi"),
    _col("shorthanded_toi", "STRING", "NULLABLE", "Shorthanded TOI.",
         "Time on ice while shorthanded (MM:SS).",
         tags=["measure"], example="1:32",
         api_eq="shorthandedToi", api_src="shorthandedToi"),
    # Goalie-only
    _col("shots_against", "INT64", "NULLABLE", "Total shots against.",
         "Shots faced by this goalie in this game.", tags=["measure"], example=32,
         api_eq="saveShotsAgainst (sum)", api_src="saveShotsAgainst"),
    _col("saves", "INT64", "NULLABLE", "Total saves.",
         "Saves made. Equals shots_against - goals_against.",
         tags=["measure"], example=30,
         api_eq="(saveShotsAgainst - goalsAgainst)", api_src="(derived)"),
    _col("save_pctg", "FLOAT64", "NULLABLE", "Save percentage.",
         "Save percentage as decimal (0.0-1.0).",
         tags=["measure"], range_=(0.0, 1.0), example=0.938,
         api_eq="savePctg", api_src="savePctg"),
    _col("goals_against", "INT64", "NULLABLE", "Goals against.",
         "Goals scored against this goalie in this game.",
         tags=["measure"], example=2,
         api_eq="goalsAgainst", api_src="goalsAgainst"),
    _col("even_strength_shots_against", "INT64", "NULLABLE",
         "Even-strength shots against.", "Shots faced at even strength.",
         tags=["measure"], example=20,
         api_eq="evenStrengthShotsAgainst", api_src="evenStrengthShotsAgainst"),
    _col("power_play_shots_against", "INT64", "NULLABLE",
         "PP shots against.", "Shots faced while shorthanded.",
         tags=["measure"], example=8,
         api_eq="powerPlayShotsAgainst", api_src="powerPlayShotsAgainst"),
    _col("shorthanded_shots_against", "INT64", "NULLABLE",
         "SH shots against.", "Shots faced while on the power play.",
         tags=["measure"], example=4,
         api_eq="shorthandedShotsAgainst", api_src="shorthandedShotsAgainst"),
    _col("even_strength_goals_against", "INT64", "NULLABLE",
         "EV goals against.", "Goals allowed at even strength.",
         tags=["measure"], example=1,
         api_eq="evenStrengthGoalsAgainst", api_src="evenStrengthGoalsAgainst"),
    _col("power_play_goals_against", "INT64", "NULLABLE",
         "PP goals against.", "Goals allowed while shorthanded.",
         tags=["measure"], example=1,
         api_eq="powerPlayGoalsAgainst", api_src="powerPlayGoalsAgainst"),
    _col("shorthanded_goals_against", "INT64", "NULLABLE",
         "SH goals against.", "Goals allowed while on the power play.",
         tags=["measure"], example=0,
         api_eq="shorthandedGoalsAgainst", api_src="shorthandedGoalsAgainst"),
    _col("ingested_at", "TIMESTAMP", "REQUIRED",
         "Ingestion timestamp.",
         "UTC timestamp when this row was written.",
         tags=["meta"], example="2026-05-22T17:00:00Z",
         api_eq=None, api_src="(set by ingestion)"),
]
